projects:
- secret: some-secret
  id: realtime-todo-app
  name: Realtime Todo App
  modules:
    crud:
      mongo:
        conn: mongodb://localhost:27017
        collections:
          todos:
            isRealtimeEnabled: true
            rules:
              create:
                rule: allow
              delete:
                rule: allow
              read:
                rule: match
                eval: ==
                type: string
                f1: args.auth.id
                f2: args.find.userId
              update:
                rule: allow
        isPrimary: false
        enabled: true
    auth:
      email:
        enabled: true
        id: ""
        secret: ""
    functions:
      enabled: false
      broker: nats
      conn: nats://localhost:4222
      rules: {}
    realtime:
      enabled: true
      broker: nats
      conn: nats://localhost:4222
    fileStore:
      enabled: false
      storeType: local
      conn: ./
      endpoint: ""
      rules:
      - prefix: /
        rule:
          create:
            rule: allow
          delete:
            rule: allow
          read:
            rule: allow
ssl:
  enabled: false
  crt: ""
  key: ""
static:
  routes:
  - path: "."
    prefix: /
    host: ""
    proxy: ""
admin:
  secret: some-secret
  operation:
    mode: 0
    userId: ""
    key: ""
  users:
  - user: admin
    pass: "123"
    scopes:
      all:
      - all
deploy:
  enabled: false